ApiErrorException: make ErrorCode property's setter private.
This 1-liner was an improvement that I forgot to include in this pull
request:

https://github.com/7digital/SevenDigital.Api.Wrapper/pull/27